export enum AppointmentCancellationReason {
    CLIENT_CANCEL = 'CLIENT_CANCEL',
    CLIENT_LATE_CANCEL = 'CLIENT_LATE_CANCEL',
    MERGED = 'MERGED',
    MISTAKE = 'MISTAKE',
    NO_SHOW = 'NO_SHOW',
    STAFF_CANCEL = 'STAFF_CANCEL',
    VOIDED = 'VOIDED',
}