import { ThirdPartyService, ThirdPartyServiceMap } from "../model/ThirdPartyService";
import { WebhookType, WebhookTypeMap } from "../controllers/WebhooksController/model/WebhookType";

const baseUrl = process.env.BASE_URL!

export const webhookReceiverUri: ThirdPartyServiceMap<WebhookTypeMap<string>> = {
    [ThirdPartyService.Boulevard]: {
        [WebhookType.ContactCreated]: `${baseUrl}/services/boulevard/webhookReceiver/contactCreated`,
        [WebhookType.ContactUpdated]: `${baseUrl}/services/boulevard/webhookReceiver/contactUpdated`,
        [WebhookType.ContactMerged]: `${baseUrl}/services/boulevard/webhookReceiver/contactMerged`,
        [WebhookType.ContactDeleted]: '', // `${baseUrl}/services/boulevard/webhookReceiver/contactDeleted`,
        [WebhookType.OpportunityCreated]: '',
        [WebhookType.OpportunityDeleted]: '',
        [WebhookType.OpportunityStatusUpdate]: '',
        [WebhookType.OpportunityAssignedToUpdate]: '',
        [WebhookType.OpportunityMonetaryValueUpdate] : '',
        [WebhookType.OpportunityStageUpdate] : '',
        [WebhookType.AppointmentCreated]: `${baseUrl}/services/boulevard/webhookReceiver/appointmentCreated`,
        [WebhookType.AppointmentUpdated]: `${baseUrl}/services/boulevard/webhookReceiver/appointmentUpdated`,
        [WebhookType.AppointmentCancelled]: `${baseUrl}/services/boulevard/webhookReceiver/appointmentCancelled`,
        [WebhookType.AppointmentCompleted]: `${baseUrl}/services/boulevard/webhookReceiver/appointmentCompleted`,
        [WebhookType.AppointmentRescheduled]: `${baseUrl}/services/boulevard/webhookReceiver/appointmentRescheduled`,
        [WebhookType.AppointmentActive]: `${baseUrl}/services/boulevard/webhookReceiver/appointmentActive`,
        [WebhookType.AppointmentConfirmed]: `${baseUrl}/services/boulevard/webhookReceiver/appointmentConfirmed`,
        [WebhookType.AppointmentArrived]: `${baseUrl}/services/boulevard/webhookReceiver/appointmentArrived`,
        [WebhookType.MessageFailed]: '',
        [WebhookType.MessageSent]: '',
    },
    [ThirdPartyService.Podium]: {
        [WebhookType.ContactCreated]: `${baseUrl}/services/podium/webhookReceiver/contactCreated`,
        [WebhookType.ContactUpdated]: `${baseUrl}/services/podium/webhookReceiver/contactUpdated`,
        [WebhookType.ContactMerged]: `${baseUrl}/services/podium/webhookReceiver/contactMerged`,
        [WebhookType.ContactDeleted]: `${baseUrl}/services/podium/webhookReceiver/contactDeleted`,
        [WebhookType.OpportunityCreated]: '',
        [WebhookType.OpportunityDeleted]: '',
        [WebhookType.OpportunityStatusUpdate]: '',
        [WebhookType.OpportunityAssignedToUpdate]: '',
        [WebhookType.OpportunityMonetaryValueUpdate] : '',
        [WebhookType.OpportunityStageUpdate] : '',
        [WebhookType.AppointmentActive]: '',
        [WebhookType.AppointmentCompleted]: '',
        [WebhookType.AppointmentCancelled]: '',
        [WebhookType.AppointmentRescheduled]: '',
        [WebhookType.AppointmentCreated]: '',
        [WebhookType.AppointmentUpdated]: '',
        [WebhookType.AppointmentConfirmed]: '',
        [WebhookType.AppointmentArrived]: '',
        [WebhookType.MessageFailed]: `${baseUrl}/services/podium/webhookReceiver/messageFailed`,
        [WebhookType.MessageSent]: `${baseUrl}/services/podium/webhookReceiver/messageSent`,
    },
    // TODO - Not Implemented
    [ThirdPartyService.GoHighLevel]: {
        [WebhookType.OpportunityCreated]: `${baseUrl}/services/gohighlevel/webhookReceiver/opportunityCreated`,
        [WebhookType.OpportunityDeleted]: `${baseUrl}/services/gohighlevel/webhookReceiver/opportunityDeleted`,
        [WebhookType.OpportunityStatusUpdate]: `${baseUrl}/services/gohighlevel/webhookReceiver/opportunityStatusUpdate`,
        [WebhookType.OpportunityAssignedToUpdate]: `${baseUrl}/services/gohighlevel/webhookReceiver/opportunityAssignedToUpdate`,
        [WebhookType.OpportunityMonetaryValueUpdate] : `${baseUrl}/services/gohighlevel/webhookReceiver/opportunityMonetaryValueUpdate`,
        [WebhookType.OpportunityStageUpdate] : `${baseUrl}/services/gohighlevel/webhookReceiver/opportunityStageUpdate`,
        [WebhookType.ContactCreated]: '',
        [WebhookType.ContactUpdated]: '',
        [WebhookType.ContactMerged]: '',
        [WebhookType.ContactDeleted]: '',
        [WebhookType.AppointmentActive]: '',
        [WebhookType.AppointmentCompleted]: '',
        [WebhookType.AppointmentCancelled]: '',
        [WebhookType.AppointmentRescheduled]: '',
        [WebhookType.AppointmentCreated]: '',
        [WebhookType.AppointmentUpdated]: '',
        [WebhookType.AppointmentConfirmed]: '',
        [WebhookType.AppointmentArrived]: '',
        [WebhookType.MessageFailed]: '',
        [WebhookType.MessageSent]: '',
    }
}